name: build

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm install

      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CI: true
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm test -- --coverage --watchAll=false
          coverageLocations: 'client/coverage/lcov.info:lcov'
          debug: true
